AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Deploying a Python code snippet in AWS SAM
Resources:
  LambdaDevOpsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: Lambdaassignment/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        LambdaDevOps:
          Type: Api 
          Properties:
            Path: /Lambdaassignment
            Method: get

Outputs:
  LambdaDevOpsApi:
    Description: "API Gateway endpoint URL for Prod stage for Lambdaassignment function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/Lambdaassignment/"
  LambdaDevOpsFunction:
    Description: "Lambdaassignment Lambda Function ARN"
    Value: !GetAtt LambdaDevOpsFunction.Arn
  LambdaDevOpsFunctionIamRole:
    Description: "Implicit IAM Role created for Lambdaassignment function"
    Value: !GetAtt LambdaassignmentFunctionRole.Arn

